from random import shuffle
words = []
word_1 = input("Enter a random word: ")
word_2 = input("Enter another random word: ")
word_3 = input("Enter yet another random word: ")
word_4 = input("Enter a fourth random word: ")
word_5 = input("Enter a fith random word: ")
word_6 = input("Enter a sixth random word: ")
word_7 = input("Enter a seventh random word: ")
word_8 = input("Enter an eighth random word: ")
word_9 = input("Enter a ninth random word: ")
word_10 = input("Wow, that's a lot of words! Enter a tenth random word: ")
words.append(word_1)
words.append(word_2)
words.append(word_3)
words.append(word_4)
words.append(word_5)
words.append(word_6)
words.append(word_7)
words.append(word_8)
words.append(word_9)
words.append(word_10)
shuffle(words)
print("Here are your scrambled words:")
print(*words, sep = ' ')